# Generated by Django 5.0.6 on 2024-07-02 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_description_category_slug_category_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discriptions',
            new_name='descriptions',
        ),
    ]
