name: Python pull request workflow
on: [pull_request]
jobs:

    qa:
     name: Quality check
     runs-on: ubuntu-22.04
     steps:
        - uses: actions/checkout@v1
        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.11
        - name: Install -U pip
          run: |
            pip install -U pip
            pip install poetry
            poetry install
          env:
            POETRY_VIRTUALENS_CREATE: false

        - name: View poetry --help
          run: poetry --help

        - name: Install dependecies
          shell: bash
          run: python -m poetry install

        - name: Test
          run: |
             poetry run python manage.py test
        - name: Wemake Python Stylguide
          uses: wemake-services/wemake-python-styleguide@0.16.0
          continue-on-error: true
          with:
            reporter: 'github-pr-review'
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}